apiVersion: v1
kind: Service
metadata:
  labels:
    name: influxdb
    app : monitoring
  name: influxdb
spec:
  type: LoadBalancer
  ports:
  - port: 8086
  selector:
    app: monitoring
    tier: influxdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: monitoring
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
      tier: influxdb
  template:
    metadata:
      labels:
        app: monitoring
        tier: influxdb
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb
        image: custom-influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          hostPort: 8086
        env:
        - name: INFLUXDB_DB
          value: influxdb
        - name: INFLUXDB_DB
          value: influxdb
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
