apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  ports:
    - port: 80
  selector:
    app: ft_services
    tier: wordpress
  type: LoadBalancer

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: wordpress
    spec:
      containers:
      - image: custom-wordpress:latest
        imagePullPolicy: Never
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: localhost
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: pass1234
        - name: WORDPRESS_TABLE_PREFIX
          value: wp_
        ports:
        - containerPort: 80
          hostPort: 5050
          name: wordpress
