apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: ft_services
spec:
  ports:
  - port: 5000
    targetPort: 5000

  selector:
    app: ft_services
    tier: phpmyadmin
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 5000
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
