FROM grafana/grafana
COPY dash.json /etc/grafana/provisioning/dashboards/
COPY dash2.json /etc/grafana/provisioning/dashboards/
COPY dash3.json /etc/grafana/provisioning/dashboards/
COPY dash4.json /etc/grafana/provisioning/dashboards/
COPY dash.yaml /etc/grafana/provisioning/dashboards/
