FROM grafana/grafana
COPY dash_ftps.json /etc/grafana/provisioning/dashboards/
COPY dash_grafana.json /etc/grafana/provisioning/dashboards/
COPY dash_influxdb.json /etc/grafana/provisioning/dashboards/
COPY dash_mysql.json /etc/grafana/provisioning/dashboards/
COPY dash_nginx.json /etc/grafana/provisioning/dashboards/
COPY dash_pma.json /etc/grafana/provisioning/dashboards/
COPY dash_wp.json /etc/grafana/provisioning/dashboards/
COPY dash.yaml /etc/grafana/provisioning/dashboards/
